server:
  port: 8083
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://ep-green-boat-a8fcf0m2-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_GWB6Myck8LnR
    driverClassName: org.postgresql.Driver
